### ISSUE TITLE
Crash selecting leftover Caffeine entry in Docks window

### ISSUE THREAD

**Issue by cogwheel** [caffeinetv/obs-studio#65]
Repro steps:

- Start COBS
- Open Settings > Stream
- Sign in to caffeine
- Close settings window so that the Caffeine window appears
- Open Settings > Stream
- Disconnect account
- Close settings window
- Select View > Docks > Caffeine

Expected behavior:

Caffeine entry should be removed from docks menu when the account is disconnected

**Comment by prateekshadas** [comment]
This is fixed so closing this one.
